name: kassapro
description: "Kassapro — Премиум учет долгов, заметок и ИИ-аналитика"
publish_to: 'none'
version: 3.3.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.0
  http: ^1.2.2
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
